### PR TITLE
postgres DB integration with UI

### PR DESCRIPTION
**Pull request by mike-khor**
Major integrations in our UI to our DB:
- conversations in UI are now tracked in DB (prod or local dev, depending on which one we choose).
  - upon refreshing a window mid-conversation, the conversation will not be terminated, and can be continued on
- patient has the ability to terminate conversation, which allows them to start a new conversation (which starts a new ConversationSession).
- patient sign-up page

To choose which DB to connect to, one would need to go to `.env` and uncomment for either Dev (local) or Prod. Please see .env.example for details, and look to Lastpass for login details to our db

### CODE REVIEW

**Comment by garyukong** [comment]
Thanks Mike. The code looks good Mike but I think I might need help understanding how to make it work.

I managed to spin up a local instance of PostgreSQL based on notes from your notebook, but still haven't been able to get the streamlit app running. I'm getting this error in the streamlit app:
`ProgrammingError: (psycopg2.errors.UndefinedTable) relation "patients" does not exist LINE 2: FROM patients ^ [SQL: SELECT patients.id AS patients_id, patients.username AS patients_username, patients.first_name AS patients_first_name, patients.last_name AS patients_last_name, patients.created_at AS patients_created_at, patients.updated_at AS patients_updated_at, patients.email AS patients_email, patients.password AS patients_password, patients.healthcare_provider_id AS patients_healthcare_provider_id FROM patients] (Background on this error at: https://sqlalche.me/e/20/f405)` likely because I'm missing a step of creating tables

Do you think you could make a readme specifying steps required to spin up the streamlit app (including setting up the SQL server, the requisite tables, and the connections between the chatbot and the server)?

**Comment by garyukong** [comment]
I also think we could do with readme / diagrams that explains how do each of the different classes interact with each other and the SQL server? From reviewing the code I think I have some understanding of how things interact with one another but I'm not sure I am 100% and an explanation from your part would be very helpful.

A nice to have (but not necessary) is something that shows the schemas of our tables and the relationships between one another.

Think we were meant to talk about this anyhow in our presentation on Monday?

**Comment by mike-khor** [comment]
> Thanks Mike. The code looks good Mike but I think I might need help understanding how to make it work.

@garyukong for sure, I'll make a readme for how to set up the local postgres instance + the connections. good point about relevance to Monday as well.

**Comment by garyukong** [comment]
Hey Mike. Thanks for the readme.

Ran into this error running make create_dev_db:

` make create_dev_db                                                                                                                                                                                                                                                                           ─╯
# ensure that postgres is running
brew services start postgresql
Warning: Formula postgresql was renamed to postgresql@14.
Service `postgresql@14` already started, use `brew services restart postgresql@14` to restart.
# first, drop the database if it exists
psql -c "DROP DATABASE IF EXISTS reco" postgres
DROP DATABASE
# create the database
createdb reco
# create the tables using alembic_upgrade
make alembic_upgrade env=DEV
POSTGRES_DB_ENVIRONMENT=DEV cd reco_analysis/data_model && poetry run alembic upgrade head
The currently activated Python version 3.12.3 is not supported by the project (3.11.7).
Trying to find and use a compatible version. 
Using python3 (3.11.7)
2024-07-04 18:20:45.522 | INFO     | reco_analysis.config:<module>:11 - PROJ_ROOT path is: /Users/garykong/Library/CloudStorage/GoogleDrive-garykong91@gmail.com/My Drive/Schoolwork/recoverycompanion/reco_analysis
Traceback (most recent call last):
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/config.py", line 636, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/garykong/Library/CloudStorage/GoogleDrive-garykong91@gmail.com/My Drive/Schoolwork/recoverycompanion/reco_analysis/reco_analysis/data_model/alembic/env.py", line 85, in <module>
    run_migrations_online()
  File "/Users/garykong/Library/CloudStorage/GoogleDrive-garykong91@gmail.com/My Drive/Schoolwork/recoverycompanion/reco_analysis/reco_analysis/data_model/alembic/env.py", line 69, in run_migrations_online
    connectable = engine_from_config(
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 820, in engine_from_config
    return create_engine(url, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 546, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 842, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garykong/Library/Caches/pypoetry/virtualenvs/reco-analysis-pAZMHX9p-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/url.py", line 908, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string ''
make[1]: *** [alembic_upgrade] Error 1
make: *** [create_dev_db] Error 2`

**Review by garyukong — APPROVED** [review]
Looks good! Something to bear in mind is that latency is worse when we don't use the database instead of the in-memory store.

**Pull request merged**
